### ISSUE TITLE
sbds_tx_delegate_vesting_shares fields mispelled

### ISSUE THREAD

**Issue by inertia186** [steemit/sbds#64]
The columns `delgator` and `delgatee` are misspelled and not being ingested.

https://github.com/steemit/sbds/blob/017394599855bb9ac58cfb9e4545f7a8dc56d68e/sbds/storages/db/tables/tx.py#L1068

![image](https://cloud.githubusercontent.com/assets/494368/26751451/b91e3330-47ee-11e7-977d-57e5a3ec6bf6.png)

**Comment by john-g-g** [comment]
Thanks @inertia186. As the lead developer for sbds at Steemit, I'm very luck to have support like yours from the Steem community. This bug about was fixed  on June 6 in commit f25799ee94aaa , it just wasn't closed in the commit message. I welcome any other bugs, feedback or questions you have, so don't hesitate to reach out to me any time.
