### ISSUE TITLE
Inconsistency on column sizes for "memo" column across tables

### ISSUE THREAD

**Issue by recrypto** [steemit/sbds#67]
tx_transfers 
memo = text

tx_transfer_from_savings 
memo = varchar(250)

tx_transfer_to_savings 
memo = varchar(250)

What should be the right data type for memo?

**Comment by john-g-g** [comment]
Hi @recrypto , thanks for your help with this. The correct answer for these field sizes is defined in the blockchain here: https://github.com/steemit/steem/blob/stable/libraries/protocol/steem_operations.cpp#L490
it says : 
```
void transfer_to_savings_operation::validate()const {
      validate_account_name( from );
      validate_account_name( to );
      FC_ASSERT( amount.amount > 0 );
      FC_ASSERT( amount.symbol == STEEM_SYMBOL || amount.symbol == SBD_SYMBOL );
      FC_ASSERT( memo.size() < STEEMIT_MAX_MEMO_SIZE, "Memo is too large" );
      FC_ASSERT( fc::is_utf8( memo ), "Memo is not UTF8" );
   }
   void transfer_from_savings_operation::validate()const {
      validate_account_name( from );
      validate_account_name( to );
      FC_ASSERT( amount.amount > 0 );
      FC_ASSERT( amount.symbol == STEEM_SYMBOL || amount.symbol == SBD_SYMBOL );
      FC_ASSERT( memo.size() < STEEMIT_MAX_MEMO_SIZE, "Memo is too large" );
      FC_ASSERT( fc::is_utf8( memo ), "Memo is not UTF8" );
   }
```
`STEEMIT_MAX_MEMO_SIZE` can be found this way:
```
$ curl -H 'Content-Type: application/json' \
-d '{"id":1,"jsonrpc":"1.0", "method": "get_config"}' \
https://steemd.steemit.com | jq '.result.STEEMIT_MAX_MEMO_SIZE' 
```
It reports the `STEEMIT_MAX_MEMO_SIZE` as 2048

I've made the changes and they are now merged with master. I welcome any other bugs, feedback or questions you have, so don't hesitate to reach out to me any time.
